# Generated by Django 4.2.6 on 2023-10-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zipcoce',
            new_name='zipcode',
        ),
    ]
